name: Deploy Deepl Bot to VPS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/var/opt/deepl-translate-bot"

      - name: SSH into VPS, install, build and restart PM2 app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/opt/deepl-translate-bot
            yarn install --frozen-lockfile
            yarn build
            pm2 restart deepl-bot || pm2 start ecosystem.config.js
            pm2 save
